<a href="https://colab.research.google.com/github/krahul2024/machine-learning/blob/main/tensors/tensors_one.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#@title Imports
import tensorflow as tf
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')


## Introduction

In [37]:
# creating tensors with tf.constant
scalar = tf.constant(10)
print(scalar)
scalar.ndim # this is for getting the dimension of tensor , here it is scalar


tf.Tensor(10, shape=(), dtype=int32)


0

In [38]:
vector = tf.constant([10, 30])
vector.ndim   # dimension of the vector , here it is 1

1

In [39]:
matrix = tf.constant([[10, 22],[12,211]])
print('No. of dimensions for matrix are : ', matrix.ndim)
matrix # this is 2d so ndim -> no. of dimensions for this one will be 2

No. of dimensions for matrix are :  2


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 10,  22],
       [ 12, 211]], dtype=int32)>

In [40]:
 matrix_one = tf.constant([[10,11,12],[12,23,25],[1., 12., 122.]], dtype = tf.float32)
 matrix_one.ndim

2

### Creating tensors with `tf.Variable`

In [52]:
var_tensor = tf.Variable([10,7])
const_tensor = tf.constant([10,11])
var_tensor , const_tensor
rand_tensor = tf.random

Creating random tensors with tensorflow

`tf.random.uniform/normal( shape, minval=0, maxval=None, dtype=tf.dtypes.float32, seed=None,  name=None)`

uniform for uniform distribution,
normal for normal distribution

In [53]:
rand_tensor = tf.random.uniform([2,5,3,4], minval = 0, maxval = 100, dtype = tf.dtypes.float32, seed = 11) # this is for getting uniformly distributed values
rand_tensor, rand_tensor.ndim

(<tf.Tensor: shape=(2, 5, 3, 4), dtype=float32, numpy=
 array([[[[36.499714  , 48.88778   , 91.32618   , 25.193262  ],
          [16.582823  , 97.52257   , 44.004105  , 75.50574   ],
          [63.21428   , 20.446682  , 21.20415   , 19.827986  ]],
 
         [[27.02744   , 64.45725   , 15.8629055 , 89.46597   ],
          [79.794586  , 19.316542  , 59.31648   , 51.863716  ],
          [37.834156  , 14.249444  ,  0.78237057, 83.17368   ]],
 
         [[62.441315  , 55.93804   , 18.659342  , 18.111538  ],
          [31.55421   , 64.10766   ,  5.046737  , 14.97761   ],
          [28.34264   , 91.52949   , 71.9794    , 99.49996   ]],
 
         [[40.002274  , 49.299408  , 15.229475  , 89.02998   ],
          [91.25129   , 44.708668  , 34.167706  , 80.94463   ],
          [38.065636  , 33.97881   , 61.49669   , 74.61533   ]],
 
         [[91.45552   , 47.018085  , 17.427181  , 30.804873  ],
          [43.40054   , 37.342487  , 68.96394   , 28.43132   ],
          [34.245228  , 99.00737   , 

### shuffling  
`tf.random.shuffle(
    value, seed=None, name=None
)`

This shuffles along the first dimension

In [ ]:
real = tf.constant([[10,122,1322],[12,612,322],[11, 212,102]])
shuffled = tf.random.shuffle(real)
shuffled, real

Shuffling is useful  in the cases when we have sequential data of different types .
> let's say we have 100 images of first type , 100 images of second type, now if we feed this to NN , then it will learn first 100 and then rest, now using shuffling we can shuffle the order and mix both types of images and the model can learn simultaneously about both types of images.

### Other ways of creating tensors

`tf.ones([2,3,4])  for all ones`

 `tf.zeros([5,3,4]) for all zeros  `

> Also we can turn numpy arrays into tensors using various methods
``tf.constant(np_arr)`` or `tf.convert_to_tensor(np_arr)` .

> The difference between numpy arrays and tensors is , tensors can be run on a GPU.

> Also we can change the shape , let's say there are total of 30 integers in np_arr , then we can get different shape of tensor as long as product of dimensions of new tensor is equal to the no. of elements in np array.

In [67]:
np_arr = np.random.randint(100, size = ([5,3,4]))
converted_tensor_same_dims = tf.convert_to_tensor(np_arr)
converted_tensor_diff_dims = tf.constant(np_arr, shape = (2,3,2,5))
converted_tensor_diff_dims, converted_tensor_diff_dims.ndim

(<tf.Tensor: shape=(2, 3, 2, 5), dtype=int64, numpy=
 array([[[[36, 78, 31, 70, 48],
          [52, 10,  2, 65, 16]],
 
         [[62, 25,  8, 64, 79],
          [38, 57, 66, 93, 76]],
 
         [[22, 15, 46, 10, 49],
          [47, 56, 29, 38, 37]]],
 
 
        [[[91, 61, 95, 11, 28],
          [15, 20, 37, 22, 82]],
 
         [[80, 57, 47, 16, 40],
          [ 5, 18, 18, 39, 97]],
 
         [[94, 70, 44, 43, 28],
          [17, 56,  3, 29, 75]]]])>,
 4)