<a href="https://colab.research.google.com/github/krahul2024/machine-learning/blob/main/tensors/tensors_one.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [87]:
#@title Imports
import tensorflow as tf
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## Introduction

In [88]:
# creating tensors with tf.constant
scalar = tf.constant(10)
print(scalar)
scalar.ndim # this is for getting the dimension of tensor , here it is scalar


tf.Tensor(10, shape=(), dtype=int32)


0

In [89]:
vector = tf.constant([10, 30])
vector.ndim   # dimension of the vector , here it is 1

1

In [90]:
matrix = tf.constant([[10, 22],[12,211]])
print('No. of dimensions for matrix are : ', matrix.ndim)
matrix # this is 2d so ndim -> no. of dimensions for this one will be 2

No. of dimensions for matrix are :  2


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 10,  22],
       [ 12, 211]], dtype=int32)>

In [91]:
 matrix_one = tf.constant([[10,11,12],[12,23,25],[1., 12., 122.]], dtype = tf.float32)
 matrix_one.ndim

2

### Creating tensors with `tf.Variable`

In [92]:
var_tensor = tf.Variable([10,7])
const_tensor = tf.constant([10,11])
var_tensor , const_tensor
rand_tensor = tf.random

Creating random tensors with tensorflow

`tf.random.uniform/normal( shape, minval=0, maxval=None, dtype=tf.dtypes.float32, seed=None,  name=None)`

uniform for uniform distribution,
normal for normal distribution

In [93]:
rand_tensor = tf.random.uniform([2,5,3,4], minval = 0, maxval = 100, dtype = tf.dtypes.float32, seed = 11) # this is for getting uniformly distributed values
rand_tensor, rand_tensor.ndim

(<tf.Tensor: shape=(2, 5, 3, 4), dtype=float32, numpy=
 array([[[[99.17426   , 43.457474  , 74.8842    , 48.56793   ],
          [92.41731   , 69.03195   ,  7.3939443 ,  5.887401  ],
          [95.66044   ,  6.8011284 , 48.39058   , 72.129074  ]],
 
         [[85.19228   , 24.99324   , 20.68056   , 73.96255   ],
          [95.05777   , 48.89748   , 49.755836  , 69.14302   ],
          [21.295761  , 74.53889   , 94.35124   , 20.163023  ]],
 
         [[56.15524   , 33.069347  , 46.155537  , 48.076294  ],
          [63.95413   , 75.65478   ,  9.761786  , 73.88579   ],
          [24.63132   , 48.72495   , 75.65516   , 30.644775  ]],
 
         [[79.64442   , 79.733864  , 81.45761   , 69.145325  ],
          [38.53233   , 71.9818    , 18.157446  , 54.149174  ],
          [28.692509  , 43.7253    , 68.49827   , 48.51942   ]],
 
         [[36.78428   , 82.5075    , 61.040543  , 13.864792  ],
          [67.056465  , 47.48404   , 78.96921   , 99.735245  ],
          [53.922558  , 70.492615  , 

### shuffling  
`tf.random.shuffle(
    value, seed=None, name=None
)`

This shuffles along the first dimension

In [94]:
real = tf.constant([[10,122,1322],[12,612,322],[11, 212,102]])
shuffled = tf.random.shuffle(real)
shuffled, real

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[  11,  212,  102],
        [  10,  122, 1322],
        [  12,  612,  322]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[  10,  122, 1322],
        [  12,  612,  322],
        [  11,  212,  102]], dtype=int32)>)

Shuffling is useful  in the cases when we have sequential data of different types .
> let's say we have 100 images of first type , 100 images of second type, now if we feed this to NN , then it will learn first 100 and then rest, now using shuffling we can shuffle the order and mix both types of images and the model can learn simultaneously about both types of images.

### Other ways of creating tensors

`tf.ones([2,3,4])  for all ones`

 `tf.zeros([5,3,4]) for all zeros  `

> Also we can turn numpy arrays into tensors using various methods
``tf.constant(np_arr)`` or `tf.convert_to_tensor(np_arr)` .

> The difference between numpy arrays and tensors is , tensors can be run on a GPU.

> Also we can change the shape , let's say there are total of 30 integers in np_arr , then we can get different shape of tensor as long as product of dimensions of new tensor is equal to the no. of elements in np array.

In [95]:
np_arr = np.random.randint(100, size = ([5,3,4]))
converted_tensor_same_dims = tf.convert_to_tensor(np_arr)
converted_tensor_diff_dims = tf.constant(np_arr, shape = (2,3,2,5))
converted_tensor_diff_dims, converted_tensor_diff_dims.ndim

(<tf.Tensor: shape=(2, 3, 2, 5), dtype=int64, numpy=
 array([[[[54, 75, 66, 62, 87],
          [91, 52, 68, 38, 19]],
 
         [[43,  0, 38, 94, 83],
          [97,  9, 97, 24, 15]],
 
         [[81, 72, 48, 29, 55],
          [26, 15, 90, 17, 95]]],
 
 
        [[[39,  3, 19, 60, 38],
          [80, 48, 16, 61, 34]],
 
         [[22, 53, 80, 90, 63],
          [10,  0, 23, 71, 70]],
 
         [[36, 55, 66, 72, 48],
          [42, 23, 15, 19, 17]]]])>,
 4)

### Tensor properties
* Shape : it is just information about different dimesions , like 2x4x5.
* Rank : The no. of tensor dimensions , scalar -> 0, array/vector -> 1 , matrix -> 2 and so on ...
* Axis  or Dimension  : A particular axis or dimension , indexing is from 0 , so for 0th -> x-axis  and 1st -> y-axis and so on ..
* Size : This is total no. of elements  in the tensor

In [96]:
# rank 7 tensor
rank_sev_tensor = tf.ones([2,3,4,2,3,4,2]) * 12
print('Shape ' , rank_sev_tensor.shape)
print('Rank ', rank_sev_tensor.ndim)
print('Size ' , tf.size(rank_sev_tensor).numpy())
for i in range(7):
    print('No of elements along' , i+1 ,'th  axis : ', rank_sev_tensor.shape[i])

print('\nFirst two elements of each dimension ')
rank_sev_tensor[:2, :2, :2, :2, :2, :2, :2]

Shape  (2, 3, 4, 2, 3, 4, 2)
Rank  7
Size  1152
No of elements along 1 th  axis :  2
No of elements along 2 th  axis :  3
No of elements along 3 th  axis :  4
No of elements along 4 th  axis :  2
No of elements along 5 th  axis :  3
No of elements along 6 th  axis :  4
No of elements along 7 th  axis :  2

First two elements of each dimension 


<tf.Tensor: shape=(2, 2, 2, 2, 2, 2, 2), dtype=float32, numpy=
array([[[[[[[12., 12.],
            [12., 12.]],

           [[12., 12.],
            [12., 12.]]],


          [[[12., 12.],
            [12., 12.]],

           [[12., 12.],
            [12., 12.]]]],



         [[[[12., 12.],
            [12., 12.]],

           [[12., 12.],
            [12., 12.]]],


          [[[12., 12.],
            [12., 12.]],

           [[12., 12.],
            [12., 12.]]]]],




        [[[[[12., 12.],
            [12., 12.]],

           [[12., 12.],
            [12., 12.]]],


          [[[12., 12.],
            [12., 12.]],

           [[12., 12.],
            [12., 12.]]]],



         [[[[12., 12.],
            [12., 12.]],

           [[12., 12.],
            [12., 12.]]],


          [[[12., 12.],
            [12., 12.]],

           [[12., 12.],
            [12., 12.]]]]]],





       [[[[[[12., 12.],
            [12., 12.]],

           [[12., 12.],
            [12., 12.]]],


     