<a href="https://colab.research.google.com/github/krahul2024/machine-learning/blob/main/tensors/tensors_one.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#@title Imports
import tensorflow as tf
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')


## Introduction

In [2]:
# creating tensors with tf.constant
scalar = tf.constant(10)
print(scalar)
scalar.ndim # this is for getting the dimension of tensor , here it is scalar


tf.Tensor(10, shape=(), dtype=int32)


0

In [3]:
vector = tf.constant([10, 30])
vector.ndim   # dimension of the vector , here it is 1

1

In [4]:
matrix = tf.constant([[10, 22],[12,211]])
print('No. of dimensions for matrix are : ', matrix.ndim)
matrix # this is 2d so ndim -> no. of dimensions for this one will be 2

No. of dimensions for matrix are :  2


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 10,  22],
       [ 12, 211]], dtype=int32)>

In [5]:
 matrix_one = tf.constant([[10,11,12],[12,23,25],[1., 12., 122.]], dtype = tf.float32)
 matrix_one.ndim

2

### Creating tensors with `tf.Variable`

In [6]:
var_tensor = tf.Variable([10,7])
const_tensor = tf.constant([10,11])
var_tensor , const_tensor
rand_tensor = tf.random

Creating random tensors with tensorflow

`tf.random.uniform/normal( shape, minval=0, maxval=None, dtype=tf.dtypes.float32, seed=None,  name=None)`

uniform for uniform distribution,
normal for normal distribution

In [7]:
rand_tensor = tf.random.uniform([2,5,3,4], minval = 0, maxval = 100, dtype = tf.dtypes.float32, seed = 11) # this is for getting uniformly distributed values
rand_tensor, rand_tensor.ndim

(<tf.Tensor: shape=(2, 5, 3, 4), dtype=float32, numpy=
 array([[[[ 8.955086  , 38.965607  , 50.471367  , 97.1078    ],
          [29.068172  , 20.606554  ,  2.5980473 , 75.37996   ],
          [76.30501   , 93.53983   , 35.56894   , 38.42145   ]],
 
         [[90.65317   ,  7.8276157 ,  3.8346648 , 94.85524   ],
          [48.96165   , 66.08224   , 32.94338   , 74.87129   ],
          [71.98417   , 29.033672  ,  6.5448523 , 72.86576   ]],
 
         [[89.438995  , 47.61218   , 28.168833  , 40.286423  ],
          [98.88345   , 92.16825   , 85.60416   , 42.051865  ],
          [55.047966  , 62.03946   , 55.400776  , 70.20739   ]],
 
         [[40.816223  , 23.5878    , 13.845992  , 21.131754  ],
          [68.6862    , 42.837547  , 50.798977  ,  6.447196  ],
          [75.7252    , 83.00557   , 61.14533   , 10.852218  ]],
 
         [[44.736446  , 10.361624  , 89.804146  , 58.821404  ],
          [ 2.897966  , 47.168648  , 22.799599  , 17.44238   ],
          [46.535194  , 71.60003   , 

### shuffling  
`tf.random.shuffle(
    value, seed=None, name=None
)`

This shuffles along the first dimension

In [8]:
real = tf.constant([[10,122,1322],[12,612,322],[11, 212,102]])
shuffled = tf.random.shuffle(real)
shuffled, real

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[  12,  612,  322],
        [  10,  122, 1322],
        [  11,  212,  102]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[  10,  122, 1322],
        [  12,  612,  322],
        [  11,  212,  102]], dtype=int32)>)

Shuffling is useful  in the cases when we have sequential data of different types .
> let's say we have 100 images of first type , 100 images of second type, now if we feed this to NN , then it will learn first 100 and then rest, now using shuffling we can shuffle the order and mix both types of images and the model can learn simultaneously about both types of images.

### Other ways of creating tensors

`tf.ones([2,3,4])  for all ones`

 `tf.zeros([5,3,4]) for all zeros  `

> Also we can turn numpy arrays into tensors using various methods
``tf.constant(np_arr)`` or `tf.convert_to_tensor(np_arr)` .

> The difference between numpy arrays and tensors is , tensors can be run on a GPU.

> Also we can change the shape , let's say there are total of 30 integers in np_arr , then we can get different shape of tensor as long as product of dimensions of new tensor is equal to the no. of elements in np array.

In [ ]:
np_arr = np.random.randint(100, size = ([5,3,4]))
converted_tensor_same_dims = tf.convert_to_tensor(np_arr)
converted_tensor_diff_dims = tf.constant(np_arr, shape = (2,3,2,5))
converted_tensor_diff_dims, converted_tensor_diff_dims.ndim

### Tensor properties
* Shape : it is just information about different dimesions , like 2x4x5.
* Rank : The no. of tensor dimensions , scalar -> 0, array/vector -> 1 , matrix -> 2 and so on ...
* Axis  or Dimension  : A particular axis or dimension , indexing is from 0 , so for 0th -> x-axis  and 1st -> y-axis and so on ..
* Size : This is total no. of elements  in the tensor

In [ ]:
# rank 7 tensor
rank_sev_tensor = tf.ones([2,3,4,2,3,4,2]) * 12
print('Shape ' , rank_sev_tensor.shape)
print('Rank ', rank_sev_tensor.ndim)
print('Size ' , tf.size(rank_sev_tensor).numpy())
for i in range(7):
    print('No of elements along' , i+1 ,'th  axis : ', rank_sev_tensor.shape[i])

print('\nFirst two elements of each dimension ')
rank_sev_tensor[:2, :2, :2, :2, :2, :2, :2]

### Adding new dimension to our tensor
> It just adds another dimension such that
let's say original dimension is `3x4` then new dimension added makes the tensor have dimension as `3x4x1`.

In [ ]:
rank_two_tensor = tf.constant([[10,12,122],[11,519,102]])
# converting or adding another dimension
rank_three_tensor = rank_two_tensor[..., tf.newaxis]
rank_two_tensor, rank_three_tensor

Alternative to `tf.newaxis`
```
tf.expand_dims(
    input, axis, name=None
)
```
we can expand along any of the dimension using it.

In [ ]:
expanded_tensor = tf.expand_dims(rank_two_tensor, axis = -1) # expand the last or final axis
expanded_tensor

### Tensor operations
*Basic operations* : +, -, *, /

In [ ]:
tensor = tf.constant([[10,143],[121,940]])
tensor + 10 , tensor - 11 , tensor * 6, tensor / 12, tensor * tensor , tf.multiply(tensor, 100)

### Matrix multiplication
 *for matrix multiplication or dot product of two matrices  -> matrix_one * matrix_two ,
 let's say we have matrix_one  -> nxm,  matrix_two ->  axb,
to calculate dot product of both matrices  ->  `''a == m'' ` must be true
this gives us resultant matrix with dimension n x b
If we do this matrix_one * matrix_two , this gives element wise multiplication in tensorflow,
to get dot product, `tf.matmul` is used*



In [32]:
tensor = tf.constant([[11,123, 31],[19,101,12],[5,38,21]])
print(tensor * tensor , '\n') # element wise multiplication
# both of these can be used for matrix multiplication or dot product , keep in mind this example is square matrix but
# multiplying the non-square matrix with itself for dot product , will give an error so it is better to multiply the matrix with transpose or reshape the matrix
print('Matrix multiplication\n', (tensor @ tensor).numpy(), '\n') # this is from python
print('Matrix multiplication\n' ,tf.matmul(tensor, tensor ).numpy())

tf.Tensor(
[[  121 15129   961]
 [  361 10201   144]
 [   25  1444   441]], shape=(3, 3), dtype=int32) 

Matrix multiplication
 [[ 2613 14954  2468]
 [ 2188 12994  2053]
 [  882  5251  1052]] 

Matrix multiplication
 [[ 2613 14954  2468]
 [ 2188 12994  2053]
 [  882  5251  1052]]


Using reshape to adjust dimensions for non-square matrices

In [37]:
tensor = tf.constant([[11,123, 31],[19,101,12]])
tensor_reshape = tf.reshape(tensor, shape = (3,2))
print('Matrix Multiplication \n', tf.matmul(tensor, tensor_reshape).numpy())

Matrix Multiplication 
 [[7065 4062]
 [4552 4400]]
