<a href="https://colab.research.google.com/github/krahul2024/machine-learning/blob/main/tensors/tensors_one.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#@title Imports
import tensorflow as tf
import numpy as np
import pandas as pd
from google.colab import drive
import tensorflow_probability as tfp
drive.mount('/content/drive')


Mounted at /content/drive


## Introduction - 0

In [39]:
# creating tensors with tf.constant
scalar = tf.constant(10)
print(scalar)
scalar.ndim # this is for getting the dimension of tensor , here it is scalar


tf.Tensor(10, shape=(), dtype=int32)


0

In [40]:
vector = tf.constant([10, 30])
vector.ndim   # dimension of the vector , here it is 1

1

In [41]:
matrix = tf.constant([[10, 22],[12,211]])
print('No. of dimensions for matrix are : ', matrix.ndim)
matrix # this is 2d so ndim -> no. of dimensions for this one will be 2

No. of dimensions for matrix are :  2


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 10,  22],
       [ 12, 211]], dtype=int32)>

In [42]:
 matrix_one = tf.constant([[10,11,12],[12,23,25],[1., 12., 122.]], dtype = tf.float32)
 matrix_one.ndim

2

### Creating tensors with `tf.Variable`

In [43]:
var_tensor = tf.Variable([10,7])
const_tensor = tf.constant([10,11])
var_tensor , const_tensor
rand_tensor = tf.random

Creating random tensors with tensorflow

`tf.random.uniform/normal( shape, minval=0, maxval=None, dtype=tf.dtypes.float32, seed=None,  name=None)`

uniform for uniform distribution,
normal for normal distribution

In [44]:
rand_tensor = tf.random.uniform([2,5,3,4], minval = 0, maxval = 100, dtype = tf.dtypes.float32, seed = 11) # this is for getting uniformly distributed values
rand_tensor, rand_tensor.ndim

(<tf.Tensor: shape=(2, 5, 3, 4), dtype=float32, numpy=
 array([[[[36.499714  , 48.88778   , 91.32618   , 25.193262  ],
          [16.582823  , 97.52257   , 44.004105  , 75.50574   ],
          [63.21428   , 20.446682  , 21.20415   , 19.827986  ]],
 
         [[27.02744   , 64.45725   , 15.8629055 , 89.46597   ],
          [79.794586  , 19.316542  , 59.31648   , 51.863716  ],
          [37.834156  , 14.249444  ,  0.78237057, 83.17368   ]],
 
         [[62.441315  , 55.93804   , 18.659342  , 18.111538  ],
          [31.55421   , 64.10766   ,  5.046737  , 14.97761   ],
          [28.34264   , 91.52949   , 71.9794    , 99.49996   ]],
 
         [[40.002274  , 49.299408  , 15.229475  , 89.02998   ],
          [91.25129   , 44.708668  , 34.167706  , 80.94463   ],
          [38.065636  , 33.97881   , 61.49669   , 74.61533   ]],
 
         [[91.45552   , 47.018085  , 17.427181  , 30.804873  ],
          [43.40054   , 37.342487  , 68.96394   , 28.43132   ],
          [34.245228  , 99.00737   , 

### shuffling  
`tf.random.shuffle(
    value, seed=None, name=None
)`

This shuffles along the first dimension

In [45]:
real = tf.constant([[10,122,1322],[12,612,322],[11, 212,102]])
shuffled = tf.random.shuffle(real)
shuffled, real

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[  12,  612,  322],
        [  10,  122, 1322],
        [  11,  212,  102]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[  10,  122, 1322],
        [  12,  612,  322],
        [  11,  212,  102]], dtype=int32)>)

Shuffling is useful  in the cases when we have sequential data of different types .
> let's say we have 100 images of first type , 100 images of second type, now if we feed this to NN , then it will learn first 100 and then rest, now using shuffling we can shuffle the order and mix both types of images and the model can learn simultaneously about both types of images.

### Other ways of creating tensors

`tf.ones([2,3,4])  for all ones`

 `tf.zeros([5,3,4]) for all zeros  `

> Also we can turn numpy arrays into tensors using various methods
``tf.constant(np_arr)`` or `tf.convert_to_tensor(np_arr)` .

> The difference between numpy arrays and tensors is , tensors can be run on a GPU.

> Also we can change the shape , let's say there are total of 30 integers in np_arr , then we can get different shape of tensor as long as product of dimensions of new tensor is equal to the no. of elements in np array.

In [46]:
np_arr = np.random.randint(100, size = ([5,3,4]))
converted_tensor_same_dims = tf.convert_to_tensor(np_arr)
converted_tensor_diff_dims = tf.constant(np_arr, shape = (2,3,2,5))
converted_tensor_diff_dims, converted_tensor_diff_dims.ndim

(<tf.Tensor: shape=(2, 3, 2, 5), dtype=int64, numpy=
 array([[[[ 6,  9, 14,  0, 12],
          [31, 85, 42,  3, 60]],
 
         [[ 1, 14, 71,  9, 52],
          [18,  4, 57, 16, 12]],
 
         [[72, 28, 78, 54, 52],
          [28, 74, 19,  0, 55]]],
 
 
        [[[99, 22, 34, 31, 54],
          [70,  3, 61, 97, 79]],
 
         [[ 0, 93, 92, 56, 83],
          [72, 29, 17, 88, 55]],
 
         [[58, 30, 50, 51, 77],
          [17, 19, 83,  3, 79]]]])>,
 4)

### Tensor properties
* Shape : it is just information about different dimesions , like 2x4x5.
* Rank : The no. of tensor dimensions , scalar -> 0, array/vector -> 1 , matrix -> 2 and so on ...
* Axis  or Dimension  : A particular axis or dimension , indexing is from 0 , so for 0th -> x-axis  and 1st -> y-axis and so on ..
* Size : This is total no. of elements  in the tensor

In [47]:
# rank 7 tensor
rank_sev_tensor = tf.ones([2,3,4,2,3,4,2]) * 12
print('Shape ' , rank_sev_tensor.shape)
print('Rank ', rank_sev_tensor.ndim)
print('Size ' , tf.size(rank_sev_tensor).numpy())
for i in range(7):
    print('No of elements along' , i+1 ,'th  axis : ', rank_sev_tensor.shape[i])

print('\nFirst two elements of each dimension ')
rank_sev_tensor[:2, :2, :2, :2, :2, :2, :2]

Shape  (2, 3, 4, 2, 3, 4, 2)
Rank  7
Size  1152
No of elements along 1 th  axis :  2
No of elements along 2 th  axis :  3
No of elements along 3 th  axis :  4
No of elements along 4 th  axis :  2
No of elements along 5 th  axis :  3
No of elements along 6 th  axis :  4
No of elements along 7 th  axis :  2

First two elements of each dimension 


<tf.Tensor: shape=(2, 2, 2, 2, 2, 2, 2), dtype=float32, numpy=
array([[[[[[[12., 12.],
            [12., 12.]],

           [[12., 12.],
            [12., 12.]]],


          [[[12., 12.],
            [12., 12.]],

           [[12., 12.],
            [12., 12.]]]],



         [[[[12., 12.],
            [12., 12.]],

           [[12., 12.],
            [12., 12.]]],


          [[[12., 12.],
            [12., 12.]],

           [[12., 12.],
            [12., 12.]]]]],




        [[[[[12., 12.],
            [12., 12.]],

           [[12., 12.],
            [12., 12.]]],


          [[[12., 12.],
            [12., 12.]],

           [[12., 12.],
            [12., 12.]]]],



         [[[[12., 12.],
            [12., 12.]],

           [[12., 12.],
            [12., 12.]]],


          [[[12., 12.],
            [12., 12.]],

           [[12., 12.],
            [12., 12.]]]]]],





       [[[[[[12., 12.],
            [12., 12.]],

           [[12., 12.],
            [12., 12.]]],


     

### Adding new dimension to our tensor
> It just adds another dimension such that
let's say original dimension is `3x4` then new dimension added makes the tensor have dimension as `3x4x1`.

In [48]:
rank_two_tensor = tf.constant([[10,12,122],[11,519,102]])
# converting or adding another dimension
rank_three_tensor = rank_two_tensor[..., tf.newaxis]
rank_two_tensor, rank_three_tensor

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 10,  12, 122],
        [ 11, 519, 102]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
 array([[[ 10],
         [ 12],
         [122]],
 
        [[ 11],
         [519],
         [102]]], dtype=int32)>)

Alternative to `tf.newaxis`
```
tf.expand_dims(
    input, axis, name=None
)
```
we can expand along any of the dimension using it.

In [49]:
expanded_tensor = tf.expand_dims(rank_two_tensor, axis = -1) # expand the last or final axis
expanded_tensor

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[ 10],
        [ 12],
        [122]],

       [[ 11],
        [519],
        [102]]], dtype=int32)>

### Tensor operations
*Basic operations* : +, -, *, /

In [50]:
tensor = tf.constant([[10,143],[121,940]])
tensor + 10 , tensor - 11 , tensor * 6, tensor / 12, tensor * tensor , tf.multiply(tensor, 100)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 20, 153],
        [131, 950]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ -1, 132],
        [110, 929]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[  60,  858],
        [ 726, 5640]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[ 0.83333333, 11.91666667],
        [10.08333333, 78.33333333]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[   100,  20449],
        [ 14641, 883600]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 1000, 14300],
        [12100, 94000]], dtype=int32)>)

### Matrix multiplication
 *for matrix multiplication or dot product of two matrices  -> matrix_one * matrix_two ,
 let's say we have matrix_one  -> nxm,  matrix_two ->  axb,
to calculate dot product of both matrices  ->  `''a == m'' ` must be true
this gives us resultant matrix with dimension n x b
If we do this matrix_one * matrix_two , this gives element wise multiplication in tensorflow,
to get dot product,
 `tf.matmul` or `tf.tensordot()` is used*



In [51]:
tensor = tf.constant([[11,123, 31],[19,101,12],[5,38,21]])
print(tensor * tensor , '\n') # element wise multiplication
# both of these can be used for matrix multiplication or dot product , keep in mind this example is square matrix but
# multiplying the non-square matrix with itself for dot product , will give an error so it is better to multiply the matrix with transpose or reshape the matrix
print('Matrix multiplication\n', (tensor @ tensor).numpy(), '\n') # this is from python
print('Matrix multiplication\n' ,tf.matmul(tensor, tensor ).numpy())

tf.Tensor(
[[  121 15129   961]
 [  361 10201   144]
 [   25  1444   441]], shape=(3, 3), dtype=int32) 

Matrix multiplication
 [[ 2613 14954  2468]
 [ 2188 12994  2053]
 [  882  5251  1052]] 

Matrix multiplication
 [[ 2613 14954  2468]
 [ 2188 12994  2053]
 [  882  5251  1052]]


Using reshape to adjust dimensions for non-square matrices
> For matrices with more than 2 dimensions we need to choose an axis along which we have to transpose , like first or second or third and so on .......

In case if the matrix multiplication doesn't work on some matrix then use transpose instead of reshape, check for differences between transpose and reshape outputs .

In [52]:
tensor = tf.constant([[11,123, 31],[19,101,12]])
tensor_reshape = tf.reshape(tensor, shape = (3,2))
print('Matrix Multiplication \n', tf.matmul(tensor, tensor_reshape).numpy(), '\n')
tf.tensordot(tensor, tensor_reshape, axes = 1).numpy() # this requires axes also

Matrix Multiplication 
 [[7065 4062]
 [4552 4400]] 



array([[7065, 4062],
       [4552, 4400]], dtype=int32)

Changing the datatype of tensors

In [53]:
a = tf.constant([1.2, 232.21,143.2])
# a.dtype various types like going from lower size to higher -> reduced precision, and higher to lower  -> increased precision, from one datatype to another datatype
# from float32 to float16
b = tf.cast(a, dtype = tf.float16)
b, b.dtype
# similarly we can change from float32 to int32

(<tf.Tensor: shape=(3,), dtype=float16, numpy=array([  1.2, 232.2, 143.2], dtype=float16)>,
 tf.float16)

### Aggregating tensors
Condensing tensors from multiple values down to a smaller amount of values.
> Note : Always use floats -> float16 or float32 while calculating absolute or statistical values.

In [54]:
# getting the absolute values , note reduce is used as we are reducing the dimensions while calculating all these informations/ values
c = tf.random.uniform(shape = [3,5], minval = -110, maxval = 100, seed = 100)
print('Tensor \n' , c.numpy())
print('Max ', tf.reduce_max(c).numpy())
print('Min ', tf.reduce_min(c).numpy())
print('Mean ', tf.reduce_mean(c).numpy())
print('Sum ', tf.reduce_sum(c).numpy())
print('Standard deviation', tf.math.reduce_std(c).numpy())
print('Variance ', tf.math.reduce_variance(c).numpy())
print('Median ', tfp.stats.percentile(c, q = 50).numpy()) # use quartiles for calculation of median as median one is deprecated as of now
print('Non - zero values', tf.math.count_nonzero(c).numpy())

Tensor 
 [[ 12.681183  -50.06677   -78.87486     2.4077225 -94.263885 ]
 [ 21.071808  -35.241364  -57.737095   49.185455   41.602158 ]
 [ 93.40146    20.605469   23.984833   97.24249   -49.169678 ]]
Max  97.24249
Min  -94.263885
Mean  -0.21140544
Sum  -3.1710815
Standard deviation 56.889656
Variance  3236.4329
Median  12.681183
Non - zero values 15


Finding positional max or min

In [55]:
print('Max index \n', tf.argmax(c).numpy()) # the axis by default is axis = 0, so it will give index of max values in each of the rows , so get the position just put the cordinate as 0,rest and you will get max

Max index 
 [2 2 2 2 1]


# Introduction - 1

## Removing single dimensions

In [58]:
new_tensor = tf.random.uniform(shape = [7,5,1,1,2])
# new_tensor
new_tensor_sq = tf.squeeze(new_tensor)
new_tensor_sq.shape # this removes all the dimensions with 1 size , as there is no use of them

TensorShape([7, 5, 2])

### One hot encoding

Used for categorical data
Explanation : [One hot encoding](https://chat.openai.com/share/03481a1e-8806-421f-808c-d71213764ea9)

In [ ]:
tensor = [1, 2, 3, 4,]
tf.one_hot(tensor, depth = 8)  # using the one hot encoding function from tensorflow

In [ ]:
tf.one_hot(tensor, depth = 4, on_value = 'this is tensor tutorial', off_value = 'another sentence') # this is random/custom encoding

## Tensors and Numpy
* Tensorflow and numpy are beautiful combination.

* Tensorflow is built on tensors
*Numpy is built on arrays

In [ ]:
tensor = tf.constant(np.array([12., 11, 52]))
tensor

In [ ]:
random_tensor = tf.constant(np.random.randint(-100, 100, size = [5,2,3,2]), shape = [5,2,3,2])
random_tensor